// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class NewsTag
{
    public int NewsTagId { get; set; }

    public string NewsArticleId { get; set; }

    public int? TagId { get; set; }

    public virtual NewsArticle NewsArticle { get; set; }

    public virtual Tag Tag { get; set; }
}